apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: demo-1
spec:
  flows:
    - route:
        id: demo-route-1
        group: demo-group-1
        from:
          uri: "kamelet:kafka-not-secured-source"
          id: kafka-consumer-1
          parameters:
            topic: "public.com.neoflex.demo.client.portfolio.data"
            bootstrapServers: '185.154.195.177:9092'
          steps:
          - to:
              uri: "log:info?showAll=true&multiline=true"
              id: log-info-1
  traits:
    addons:
      telemetry:
        enabled: true
        endpoint: http://jaeger-collector:4317
    logging:
      enabled: true
      json: true
